[changelog]
header = """
# Changelog\n
"""

body = """
{% if version %}\
    ## {{ version }} - {{ codename | default(value="") }}
    **Released:** {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## Unreleased
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first | trim }} ({{ commit.id | truncate(length=7, end="") }})\
    {% endfor %}
{% endfor %}\n
"""

trim = true

[git]
conventional_commits = true
filter_commits = true
split_commits = false
sort_commits = "oldest"

commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]

commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^perf", group = "Performance" },
    { message = "^doc", group = "Documentation" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^style", skip = true },
    { message = "^test", skip = true },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(deps\\)", skip = true },
    { message = "^chore", skip = true },
]

protect_breaking_commits = false
filter_unconventional = false

link_parsers = [
    { pattern = "#(\\d+)", href = "https://github.com/betterbearmetalcode/beariscope/issues/$1" },
]