name: beariscope
description: "The ultimate FRC scouting app developed by Bear Metal, team 2046"
publish_to: 'none'

version: 26.0.0+5

environment:
  sdk: ^3.7.0
  flutter: ^3.0.0

dependencies:
  crop_your_image: ^2.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.2.1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.1.0
  libkoala:
    git: 
      url: https://github.com/bear-metal-apps/libkoala.git
      ref: v5.0.0
  logger: ^2.6.2
  material_symbols_icons: ^4.2808.1
  package_info_plus: ^9.0.0
  provider: ^6.1.2
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.5.2
  simple_icons: ^14.6.1
  url_launcher: ^6.3.1
  window_size: ^0.1.0
  hive_ce_flutter: ^2.3.3
  image: ^4.3.0
  google_fonts: ^8.0.0
  animations: ^2.1.1
  dots_indicator: ^4.0.1
  intl: ^0.20.2
  mime: ^2.0.0
  internet_connection_checker_plus: ^2.9.1+2

dependency_overrides:
  flutter_web_auth_2: 5.0.0-alpha.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Xolonium
      fonts:
        - asset: assets/fonts/Xolonium-Regular.ttf
          weight: 400
        - asset: assets/fonts/Xolonium-Bold.ttf
          weight: 700
