name: Extract Version

on:
  workflow_call:
    outputs:
      version:
        description: "The application version without build number"
        value: ${{ jobs.extract.outputs.version }}
      build_number:
        description: "The application build number"
        value: ${{ jobs.extract.outputs.build_number }}
      full_version:
        description: "The full version string (version+build)"
        value: ${{ jobs.extract.outputs.full_version }}

jobs:
  extract:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      build_number: ${{ steps.get_version.outputs.build_number }}
      full_version: ${{ steps.get_version.outputs.full_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract version from pubspec.yaml
        id: get_version
        run: |
          RAW_LINE=$(grep 'version:' pubspec.yaml | tr -d '\r')
          
          VERSION=$(echo $RAW_LINE | sed -E 's/version: +([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          BUILD=$(echo $RAW_LINE | sed -E 's/.*\+([0-9]+).*/\1/')
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD" >> $GITHUB_OUTPUT
          echo "full_version=$VERSION+$BUILD" >> $GITHUB_OUTPUT
          
          echo "Extracted version: $VERSION"
          echo "Extracted build number: $BUILD"